[package]
name = "simd-test"
version = "0.1.0"
authors = ["Martin Donlon <@wickerwaka>"]
build = "build.rs"

[profile.release]
debug = true

[dependencies]
time = "0.1.35"
cgmath = "0.11.0"
rand = "0.3.14"
simd = { git = "https://github.com/wickerwaka/simd.git" }

[build-dependencies]
gcc = "0.3"

