[package]
name = "aosoa"
version = "0.1.0"
authors = ["Martin Donlon <martin.donlon@gmail.com>"]

[profile.release]
debug = true

[dependencies]
time = "0.1.35"
cgmath = "0.11.0"
rand = "0.3.14"
simd = { path = "../simd" }
